### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by imashnake0** [imashnake0/Animite#43]
Felt like we could start working on user auth and #39 in parallel since they don't depend on each other a lot (the only potential difference is that there will be a [bottom app bar](https://m3.material.io/components/bottom-app-bar) when the user is logged in; along with some metadata). I think it's a good idea to separate this work into a new [module](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:decoupled_projects) since we'll likely need to reuse this code.
- [ ] [Create](https://docs.gradle.org/current/userguide/multi_project_builds.html) a new `auth` module.
- [ ] Implement [user authentication](https://anilist.gitbook.io/anilist-apiv2-docs/overview/oauth).
- [ ] Display the user's Media List in the Profile path.
- [ ] Allow users to log out.

**Comment by thederputy** [comment]
I'm interested in working on this. Is this up for grabs?

**Comment by imashnake0** [comment]
Sure is!
