### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by imashnake0** [imashnake0/Animite#74]
Pls bro this is an issue:

![image](https://user-images.githubusercontent.com/56754616/207404001-5edf8c0c-8f31-41e9-8076-61cdf33bcf28.png)

- [ ] Rewrite `material-color-utils` in Kotlin.

**Comment by Vipul0052** [comment]
object MaterialColorUtils {
    private val COLOR_MAP = mapOf(
        "red" to mapOf(
            "50" to "#FFEBEE",
            "100" to "#FFCDD2",
            "200" to "#EF9A9A",
            "300" to "#E57373",
            "400" to "#EF5350",
            "500" to "#F44336",
            "600" to "#E53935",
            "700" to "#D32F2F",
            "800" to "#C62828",
            "900" to "#B71C1C",
            "A100" to "#FF8A80",
            "A200" to "#FF5252",
            "A400" to "#FF1744",
            "A700" to "#D50000"
        ),
        "pink" to mapOf(
            "50" to "#FCE4EC",
            "100" to "#F8BBD0",
            "200" to "#F48FB1",
            "300" to "#F06292",
            "400" to "#EC407A",
            "500" to "#E91E63",
            "600" to "#D81B60",
            "700" to "#C2185B",
            "800" to "#AD1457",
            "900" to "#880E4F",
            "A100" to "#FF80AB",
            "A200" to "#FF4081",
            "A400" to "#F50057",
            "A700" to "#C51162"
        ),
        // ... more colors here
    )

    fun getColor(color: String, shade: String): String? {
        return COLOR_MAP[color]?.get(shade)
    }
}

**Comment by imashnake0** [comment]
?

**Comment by boswelja** [comment]
This can be closed anyways right?

**Comment by imashnake0** [comment]
Wanted to refactor to use collection APIs but I suppose that's not an issue.

**Comment by boswelja** [comment]
New issue time
