### ISSUE TITLE
It says invalid 

### ISSUE THREAD

**Issue by Solovertical** [imashnake0/Animite#78]
It shows error on installing the app
It don't have any previous version of this apk
![Screenshot_2022-12-23-11-31-51-768_com google android packageinstaller](https://user-images.githubusercontent.com/109901807/209280848-42049582-555c-4d89-b9ec-74255159537d.png)

**Comment by imashnake0** [comment]
Apologies, something about the APKs is broken (I'll fix this in my current PR), let me send one here temporarily.

**Comment by imashnake0** [comment]
[animite-release.zip](https://github.com/imashnake0/Animite/files/10292477/animite-release.zip)

**Comment by imashnake0** [comment]
I'll just use this issue to track it.

**Comment by imashnake0** [comment]
Tracking in #75.
