### ISSUE TITLE
Light mode support

### ISSUE THREAD

**Issue by EdricChan03** [imashnake0/Animite#98]
As mentioned in Discord, light mode support would be nice :kappa:

**Comment by imashnake0** [comment]
Should also be able to use more pastel like colors for light mode now that we have `material-color-utils`, the current version looks like it's straight up inverted:

![Screenshot_20230426-054054](https://user-images.githubusercontent.com/56754616/234540744-722e7cc3-584e-44aa-862e-ca047a82e34e.png)
